import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
    page: { flexDirection: 'column', backgroundColor: '#FFFFFF', padding: 40 },
    header: { marginBottom: 20, borderBottom: '2px solid #1A565E', paddingBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    headerLeft: { flexDirection: 'column' },
    logo: { width: 150, height: 'auto' }, // Adjust size as needed
    title: { fontSize: 24, color: '#1A565E', fontWeight: 'bold', textTransform: 'uppercase' },
    subtitle: { fontSize: 12, color: '#6FA388', marginTop: 5 },
    section: { margin: 10, padding: 10 },
    label: { fontSize: 10, color: '#666', marginBottom: 4, textTransform: 'uppercase' },
    value: { fontSize: 12, color: '#000', marginBottom: 15, fontFamily: 'Helvetica-Bold' },
    bodyText: { fontSize: 11, lineHeight: 1.5, marginBottom: 10, color: '#333' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, textAlign: 'center', color: '#999', borderTop: '1px solid #eee', paddingTop: 10 }
});

// The Component
export const ContractDocument = ({ data, logoUrl }) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <View style={styles.headerLeft}>
                    <Text style={styles.title}>Service Agreement</Text>
                    <Text style={styles.subtitle}>Generated by Empower VA Services</Text>
                </View>
                {logoUrl && <Image style={styles.logo} src={logoUrl} />}
            </View>

            {/* Client Details */}
            <View style={styles.section}>
                <Text style={styles.label}>Prepared For:</Text>
                <Text style={styles.value}>{data.clientName || "[Client Name]"}</Text>

                <Text style={styles.label}>Date:</Text>
                <Text style={styles.value}>{new Date().toLocaleDateString()}</Text>
            </View>

            {/* Agreement Reference */}
            <View style={styles.section}>
                <Text style={styles.label}>Agreement:</Text>
                <Text style={styles.bodyText}>
                    This contract serves as a formal agreement for the services outlined in the accepted Proposal.
                </Text>
            </View>

            {/* Legal Text */}
            <View style={styles.section}>
                <Text style={styles.label}>Terms & Conditions:</Text>
                <Text style={styles.bodyText}>
                    1. CONFIDENTIALITY: The Virtual Assistant acknowledges that they may have access to information which relates to the Client's business.
                </Text>
                <Text style={styles.bodyText}>
                    2. PAYMENT: Invoices are to be paid within 7 days of receipt.
                </Text>
                <Text style={styles.bodyText}>
                    3. TERMINATION: Either party may terminate this agreement with 14 days written notice.
                </Text>
            </View>

            {/* Footer */}
            <View style={styles.footer}>
                <Text>Empower VA Services | Operational Architecture | empowervaservices.co.uk</Text>
            </View>

        </Page>
    </Document>
);
