-- Migration Script for Phase 3.10 (Assets & Onboarding)
-- COMPLETE REPAIR VERSION
-- This script ensures ALL required tables exist. It is 100% safe to run.

-- ==========================================
-- 0. Core Infrastructure (Ensure Clients Exists First)
-- ==========================================
create table if not exists public.clients (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  -- Basic Info
  name text not null,       
  first_name text,          
  last_name text,
  email text,
  phone text,
  address text,             
  
  -- Client Management
  status text default 'Active', 
  hourly_rate numeric,
  
  -- Scope of Work 
  scope_of_work text,       
  
  -- Internal Notes
  notes text,

  constraint clients_user_id_fkey foreign key (user_id) references auth.users (id)
);

-- Safe Policy for Clients
alter table public.clients enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Users can manage their own clients') then
    create policy "Users can manage their own clients" on public.clients for all using (auth.uid() = user_id);
  end if;
end $$;

-- ==========================================
-- 1. Create 'vault_items' table (Safe Create)
-- ==========================================
create table if not exists public.vault_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  client_id uuid references public.clients(id) on delete cascade,
  title text not null,
  username text,
  password text, 
  url text,
  notes text,

  constraint vault_items_user_id_fkey foreign key (user_id) references auth.users (id)
);

alter table public.vault_items enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'vault_items' and policyname = 'Users can manage their own vault items') then
    create policy "Users can manage their own vault items" on public.vault_items for all using (auth.uid() = user_id);
  end if;
end $$;


-- ==========================================
-- 2. Create 'assets' table (Safe Create)
-- ==========================================
create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  client_id uuid references public.clients(id) on delete cascade,
  name text not null,
  file_url text not null,
  type text, 
  
  constraint assets_user_id_fkey foreign key (user_id) references auth.users (id)
);

alter table public.assets enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'assets' and policyname = 'Users can manage their own assets') then
    create policy "Users can manage their own assets" on public.assets for all using (auth.uid() = user_id);
  end if;
end $$;


-- ==========================================
-- 3. Safely Add Brand Columns to 'clients' table
-- ==========================================
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name='clients' and column_name='brand_colors') then
    alter table public.clients add column brand_colors text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name='clients' and column_name='fonts') then
    alter table public.clients add column fonts text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name='clients' and column_name='tone_of_voice') then
    alter table public.clients add column tone_of_voice text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name='clients' and column_name='communication_pref') then
    alter table public.clients add column communication_pref text;
  end if;
  
  if not exists (select 1 from information_schema.columns where table_name='clients' and column_name='tools') then
    alter table public.clients add column tools text;
  end if;
end $$;
