-- Empower VA: V4 Consolidated Schema (Master)
-- Includes: Tasks, Schedule, Timekeeper, CRM, Vault, Assets, and Client Portal Logic
-- Run this in the Supabase SQL Editor to sync everything (Safe to run multiple times).

-- ==========================================
-- 1. Tasks Table (Task Triage)
-- ==========================================
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text not null,
  quadrant text not null, -- 'do_first', 'schedule', 'delegate', 'delete'
  client_id uuid -- FK to clients table
);

-- Enable Security
alter table public.tasks enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'tasks' and policyname = 'Allow authenticated access') then
    create policy "Allow authenticated access" on public.tasks for all to authenticated using (true);
  end if;
end $$;


-- ==========================================
-- 2. Clients Table (CRM Hub)
-- ==========================================
create table if not exists public.clients (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(), -- The Admin User
  
  -- Phase 4: Linked Client Access
  linked_user_id uuid references auth.users, -- The Client User (for Portal Access)

  name text not null,       
  first_name text,          
  last_name text,
  email text,
  phone text,
  address text,             
  status text default 'Active', 
  hourly_rate numeric,
  scope_of_work text,       
  notes text,

  -- Brand Info
  brand_colors text,
  fonts text,
  tone_of_voice text,
  communication_pref text,
  tools text,

  foreign key (user_id) references auth.users (id)
);

-- Ensure linked_user_id exists if table was already created
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name='clients' and column_name='linked_user_id') then
    alter table public.clients add column linked_user_id uuid references auth.users;
  end if;
end $$;

-- Enable Security
alter table public.clients enable row level security;

-- Admin Policy: View All Clients linked to Admin
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Admins can manage their own clients') then
    create policy "Admins can manage their own clients" on public.clients for all using (auth.uid() = user_id);
  end if;
end $$;

-- Client Policy: View OWN Client Record (Read Only)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'clients' and policyname = 'Clients can view their own record') then
    create policy "Clients can view their own record" on public.clients for select using (auth.uid() = linked_user_id);
  end if;
end $$;


-- ==========================================
-- 3. Vault Items (Passwords)
-- ==========================================
create table if not exists public.vault_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  client_id uuid references public.clients(id),
  title text not null,
  username text,
  password text, 
  url text,
  notes text,

  foreign key (user_id) references auth.users (id)
);

alter table public.vault_items enable row level security;

-- Admin Policy
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'vault_items' and policyname = 'Admins can manage vault items') then
    create policy "Admins can manage vault items" on public.vault_items for all using (auth.uid() = user_id);
  end if;
end $$;

-- Client Policy: View items linked to THEIR client record
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'vault_items' and policyname = 'Clients can view their vault items') then
    create policy "Clients can view their vault items" on public.vault_items for select using (
      exists ( select 1 from public.clients c where c.id = vault_items.client_id and c.linked_user_id = auth.uid() )
    );
  end if;
end $$;


-- ==========================================
-- 4. Assets (Files)
-- ==========================================
create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  client_id uuid references public.clients(id),
  name text not null,
  file_url text not null,
  type text, 
  
  foreign key (user_id) references auth.users (id)
);

alter table public.assets enable row level security;

-- Admin Policy
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'assets' and policyname = 'Admins can manage assets') then
    create policy "Admins can manage assets" on public.assets for all using (auth.uid() = user_id);
  end if;
end $$;

-- Client Policy
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'assets' and policyname = 'Clients can view their assets') then
    create policy "Clients can view their assets" on public.assets for select using (
      exists ( select 1 from public.clients c where c.id = assets.client_id and c.linked_user_id = auth.uid() )
    );
  end if;
end $$;


-- ==========================================
-- 5. Schedule & Time Entries (Admin Only for now)
-- ==========================================
create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  start_time timestamp with time zone not null,
  duration_minutes integer default 60,
  client_id uuid references public.clients(id),
  color text default 'blue',
  foreign key (user_id) references auth.users (id)
);

alter table public.schedule enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'schedule' and policyname = 'Users can manage their own schedule') then
    create policy "Users can manage their own schedule" on public.schedule for all using (auth.uid() = user_id);
  end if;
end $$;


create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  description text not null,
  duration text not null,
  date text not null,
  client_id uuid references public.clients(id),
  foreign key (user_id) references auth.users (id)
);

alter table public.time_entries enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'time_entries' and policyname = 'Users can manage their own time entries') then
    create policy "Users can manage their own time entries" on public.time_entries for all using (auth.uid() = user_id);
  end if;
end $$;


-- ==========================================
-- 6. Storage Bucket (Safe Create)
-- ==========================================
insert into storage.buckets (id, name, public) 
values ('client-assets', 'client-assets', true)
on conflict (id) do nothing;

create policy "Authenticated users can upload assets" on storage.objects for insert to authenticated with check (bucket_id = 'client-assets');
create policy "Authenticated users can update assets" on storage.objects for update to authenticated with check (bucket_id = 'client-assets');
create policy "Authenticated users can read assets" on storage.objects for select to authenticated using (bucket_id = 'client-assets');

-- ==========================================
-- 7. Triggers: Auto-Link Function (Optional)
-- ==========================================
-- Automatically links a new User to a Client Record if emails match.

create or replace function public.link_new_user_to_client()
returns trigger as $$
begin
  -- Update the clients table where the email matches the new user's email
  update public.clients
  set linked_user_id = new.id
  where email = new.email;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger on Auth.Users creation (Safe: No Overwrites)
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.link_new_user_to_client();
  end if;
end $$;
