-- Empower VA Database Schema
-- Run this in the Supabase SQL Editor

-- 1. Tasks Table (for Task Triage / Eisenhower Matrix)
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text not null,
  quadrant text not null -- 'do_first', 'schedule', 'delegate', 'delete'
);

-- Note: user_id column will be needed later for multi-user support
-- alter table tasks add column user_id uuid references auth.users not null;

-- 2. Security (Row Level Security)
alter table tasks enable row level security;

-- Policy: Allow authenticated users to do everything (for now)
create policy "Allow authenticated access" 
on tasks for all 
to authenticated 
using (true);

-- FUTURE TABLES (Ideas)
-- create table clients (...);
-- create table time_logs (...);
-- create table invoices (...);
