-- Empower VA Database Schema
-- Run this in the Supabase SQL Editor

-- ==========================================
-- 1. Tasks Table (Task Triage)
-- ==========================================
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text not null,
  quadrant text not null, -- 'do_first', 'schedule', 'delegate', 'delete'
  client_id uuid -- FK to clients table
);

-- Enable Security
alter table tasks enable row level security;
create policy "Allow authenticated access" on tasks for all to authenticated using (true);


-- ==========================================
-- 2. Clients Table (CRM Hub)
-- ==========================================
-- Drop old table if needed (Careful: deletes data!)
-- drop table if exists public.clients;

create table if not exists public.clients (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  -- Basic Info
  name text not null,       -- Company or Full Name
  first_name text,          -- Optional: for personal greetings
  last_name text,
  email text,
  phone text,
  address text,             -- Full physical address
  
  -- Client Management
  status text default 'Active', -- Active, Lead, On Hold, Archived
  hourly_rate numeric,
  
  -- Scope of Work (The "Scope Guard")
  -- Store the agreed boundaries here to display on the dashboard
  scope_of_work text,       
  
  -- Internal Notes
  notes text,

  constraint clients_user_id_fkey foreign key (user_id) references auth.users (id)
);

-- Link Tasks to Clients (Update existing table)
-- If 'tasks' table already exists, run this line:
-- alter table tasks add column client_id uuid references public.clients(id);

-- Enable Security
alter table public.clients enable row level security;

-- Policy: Users can only see/edit their own clients
create policy "Users can manage their own clients"
on public.clients for all
using (auth.uid() = user_id);

-- ==========================================
-- 3. Schedule Table (Calendar Events)
-- ==========================================
create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  title text not null,
  start_time timestamp with time zone not null,
  duration_minutes integer default 60,
  
  -- Optional: Link to a client for context
  client_id uuid references public.clients(id),
  
  -- Visuals
  color text default 'blue', -- blue, green, lilac, slate

  constraint schedule_user_id_fkey foreign key (user_id) references auth.users (id)
);

-- Enable Security
alter table public.schedule enable row level security;

-- Policy
create policy "Users can manage their own schedule"
on public.schedule for all
using (auth.uid() = user_id);

-- Test Data (Optional - Run to populate schedule)
-- insert into schedule (title, start_time, color) values ('Client Call', now(), 'green');

-- ==========================================
-- 4. Time Entries Table (Timekeeper)
-- ==========================================
create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  description text not null,
  duration text not null, -- Stored as "01:30:00" string or similar
  date text not null, -- "MM/DD/YYYY"
  
  -- Link to a client
  client_id uuid references public.clients(id),
  
  constraint time_entries_user_id_fkey foreign key (user_id) references auth.users (id)
);

-- Enable Security
alter table public.time_entries enable row level security;

-- Policy
create policy "Users can manage their own time entries"
on public.time_entries for all
using (auth.uid() = user_id);

-- ==========================================
-- 5. Vault Items (Passwords & Tools)
-- ==========================================
create table if not exists public.vault_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  client_id uuid references public.clients(id) on delete cascade,
  title text not null,
  username text,
  password text, -- Encrypt in app or use Supabase Vault in prod
  url text,
  notes text,

  constraint vault_items_user_id_fkey foreign key (user_id) references auth.users (id)
);

alter table public.vault_items enable row level security;
create policy "Users can manage their own vault items" on public.vault_items for all using (auth.uid() = user_id);


-- ==========================================
-- 6. Client Assets (Files & Clean URLs)
-- ==========================================
create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  
  client_id uuid references public.clients(id) on delete cascade,
  name text not null,
  file_url text not null,
  type text, -- 'image/png', 'application/pdf', etc.
  
  constraint assets_user_id_fkey foreign key (user_id) references auth.users (id)
);

alter table public.assets enable row level security;
create policy "Users can manage their own assets" on public.assets for all using (auth.uid() = user_id);

-- STORAGE BUCKET POLICY (Run this if creating bucket 'client-assets')
-- insert into storage.buckets (id, name, public) values ('client-assets', 'client-assets', true);
-- create policy "Authenticated users can upload assets" on storage.objects for insert to authenticated with check (bucket_id = 'client-assets');
-- create policy "Authenticated users can update assets" on storage.objects for update to authenticated with check (bucket_id = 'client-assets');
-- create policy "Authenticated users can read assets" on storage.objects for select to authenticated using (bucket_id = 'client-assets');

-- ==========================================
-- 7. Extend Clients Table (Brand Info)
-- ==========================================
-- Run these individually if table exists:
-- alter table public.clients add column brand_colors text; 
-- alter table public.clients add column fonts text;
-- alter table public.clients add column tone_of_voice text;
-- alter table public.clients add column communication_pref text;
-- alter table public.clients add column tools text;

